/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../../../axios.client"
import type { RequestConfig, ResponseErrorConfig } from "../../../axios.client"
import type {
    GetArticleBlogApiArticlesSlugGetQueryResponse,
    GetArticleBlogApiArticlesSlugGetPathParams,
    GetArticleBlogApiArticlesSlugGet422
} from "@/packages/api/codegen"
import { getArticleBlogApiArticlesSlugGetQueryResponseSchema } from "@/packages/api/codegen"

function getGetArticleBlogApiArticlesSlugGetUrl(
    slug: GetArticleBlogApiArticlesSlugGetPathParams["slug"]
) {
    return `/blog-api/articles/${slug}` as const
}

/**
 * @description Get a single article by slug.
 * @summary Get article
 * {@link /blog-api/articles/:slug}
 */
export async function getArticleBlogApiArticlesSlugGet(
    slug: GetArticleBlogApiArticlesSlugGetPathParams["slug"],
    config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
    const { client: request = fetch, ...requestConfig } = config

    const res = await request<
        GetArticleBlogApiArticlesSlugGetQueryResponse,
        ResponseErrorConfig<GetArticleBlogApiArticlesSlugGet422>,
        unknown
    >({
        method: "GET",
        url: getGetArticleBlogApiArticlesSlugGetUrl(slug).toString(),
        ...requestConfig
    })
    return getArticleBlogApiArticlesSlugGetQueryResponseSchema.parse(res.data)
}
