/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../../../axios.client"
import type { RequestConfig, ResponseErrorConfig } from "../../../axios.client"
import type { ListArticlesBlogApiArticlesGetQueryResponse } from "../../models/commonController/ListArticlesBlogApiArticlesGet"
import { listArticlesBlogApiArticlesGetQueryResponseSchema } from "../../zod/commonController/listArticlesBlogApiArticlesGetSchema"

function getListArticlesBlogApiArticlesGetUrl() {
    return `/blog-api/articles/` as const
}

/**
 * @description List all static markdown articles.
 * @summary List articles
 * {@link /blog-api/articles/}
 */
export async function listArticlesBlogApiArticlesGet(
    config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
    const { client: request = fetch, ...requestConfig } = config

    const res = await request<
        ListArticlesBlogApiArticlesGetQueryResponse,
        ResponseErrorConfig<Error>,
        unknown
    >({
        method: "GET",
        url: getListArticlesBlogApiArticlesGetUrl().toString(),
        ...requestConfig
    })
    return listArticlesBlogApiArticlesGetQueryResponseSchema.parse(res.data)
}
