/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { headingSchemaSchema } from "./headingSchemaSchema"
import { z } from "zod"

export const articleSchemaSchema = z.object({
    slug: z.string(),
    title: z.string(),
    summary: z.union([z.string(), z.null()]).optional(),
    image_path: z.string().nullable().optional(),
    content_html: z.string(),
    headings: z.array(z.lazy(() => headingSchemaSchema))
})

export type ArticleSchemaSchema = z.infer<typeof articleSchemaSchema>
