/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod"

export const articleSummarySchemaSchema = z.object({
    slug: z.string(),
    title: z.string(),
    summary: z.union([z.string(), z.null()]).optional(),
    image_path: z.string().nullable().optional()
})

export type ArticleSummarySchemaSchema = z.infer<typeof articleSummarySchemaSchema>
