/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod"

export const headingSchemaSchema = z.object({
    level: z.number().int(),
    id: z.string(),
    text: z.string()
})

export type HeadingSchemaSchema = z.infer<typeof headingSchemaSchema>
