/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ArticleSummarySchema = {
    /**
     * @type string
     */
    slug: string
    /**
     * @type string
     */
    title: string
    summary?: string | null
    image?: string | null
}
