/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HeadingSchema } from "./HeadingSchema"

export type ArticleSchema = {
    /**
     * @type string
     */
    slug: string
    /**
     * @type string
     */
    title: string
    summary?: string | null
    image?: null
    /**
     * @type string
     */
    content_html: string
    /**
     * @type array
     */
    headings: HeadingSchema[]
}
