/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type HeadingSchema = {
    /**
     * @type integer
     */
    level: number
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    text: string
}
