/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ArticleSchema } from "../ArticleSchema"
import type { HTTPValidationError } from "../HTTPValidationError"

export type GetArticleBlogApiArticlesSlugGetPathParams = {
    /**
     * @type string
     */
    slug: string
}

/**
 * @description Successful Response
 */
export type GetArticleBlogApiArticlesSlugGet200 = ArticleSchema

/**
 * @description Validation Error
 */
export type GetArticleBlogApiArticlesSlugGet422 = HTTPValidationError

export type GetArticleBlogApiArticlesSlugGetQueryResponse = GetArticleBlogApiArticlesSlugGet200

export type GetArticleBlogApiArticlesSlugGetQuery = {
    Response: GetArticleBlogApiArticlesSlugGet200
    PathParams: GetArticleBlogApiArticlesSlugGetPathParams
    Errors: GetArticleBlogApiArticlesSlugGet422
}
