/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ArticleSummarySchema } from "@/packages/api/codegen"

/**
 * @description Successful Response
 */
export type ListArticlesBlogApiArticlesGet200 = ArticleSummarySchema[]

export type ListArticlesBlogApiArticlesGetQueryResponse = ListArticlesBlogApiArticlesGet200

export type ListArticlesBlogApiArticlesGetQuery = {
    Response: ListArticlesBlogApiArticlesGet200
    Errors: unknown
}
