/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { articleSchemaSchema } from "../articleSchemaSchema"
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema"
import { z } from "zod"

export const getArticleBlogApiArticlesSlugGetPathParamsSchema = z.object({
    slug: z.string()
})

export type GetArticleBlogApiArticlesSlugGetPathParamsSchema = z.infer<
    typeof getArticleBlogApiArticlesSlugGetPathParamsSchema
>

/**
 * @description Successful Response
 */
export const getArticleBlogApiArticlesSlugGet200Schema = z.lazy(() => articleSchemaSchema)

export type GetArticleBlogApiArticlesSlugGet200Schema = z.infer<
    typeof getArticleBlogApiArticlesSlugGet200Schema
>

/**
 * @description Validation Error
 */
export const getArticleBlogApiArticlesSlugGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export type GetArticleBlogApiArticlesSlugGet422Schema = z.infer<
    typeof getArticleBlogApiArticlesSlugGet422Schema
>

export const getArticleBlogApiArticlesSlugGetQueryResponseSchema = z.lazy(
    () => getArticleBlogApiArticlesSlugGet200Schema
)

export type GetArticleBlogApiArticlesSlugGetQueryResponseSchema = z.infer<
    typeof getArticleBlogApiArticlesSlugGetQueryResponseSchema
>
