/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { articleSummarySchemaSchema } from "../articleSummarySchemaSchema"
import { z } from "zod"

/**
 * @description Successful Response
 */
export const listArticlesBlogApiArticlesGet200Schema = z.array(
    z.lazy(() => articleSummarySchemaSchema)
)

export type ListArticlesBlogApiArticlesGet200Schema = z.infer<
    typeof listArticlesBlogApiArticlesGet200Schema
>

export const listArticlesBlogApiArticlesGetQueryResponseSchema = z.lazy(
    () => listArticlesBlogApiArticlesGet200Schema
)

export type ListArticlesBlogApiArticlesGetQueryResponseSchema = z.infer<
    typeof listArticlesBlogApiArticlesGetQueryResponseSchema
>
